engines:
  # ... CONFIG CONTENT ...
  brakeman:
    enabled: false
  duplication:
    enabled: false
    # ... CONFIG CONTENT ...
    exclude_fingerprints:
    - 46f2a7752363f6e197a854db6b6b2844
# ... CONFIG CONTENT ...
exclude_paths:
- bower_components/**/*
- app/assets/**/*
- spec/**/*
- "**/vendor/**/*"