# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8407bc346ba91bfb656e272e0ea5edf8e985a5cbeced3ecae6d0a6d6d2db6161902e124bdeab43d73c7a15554c03eba4b661be075ea2e37ef9399b6aede0dcd0

test:
  secret_key_base: 3dfd35bce945a9281cbf93fcc11985a57d2e452f169b4c7f16f0c9cc79257f3314ee3bee2cd04c082c60089089fe7804d57d7faca7d31e90911df45d9a23744b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
